on:
    push:
jobs:
    # Build job
    build:
        if: github.actor == 'stuyk'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.ref }}
            - name: Setup NodeJS
              uses: actions/setup-node@v3
            - name: Install and Build 🔧
              run: |
                  npm install
                  npm i --save-dev typedoc typedoc-plugin-external-resolver typedoc-plugin-missing-exports typedoc-plugin-markdown --force
                  npm run docs
            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: docs
            - name: Invoke Documentation Build
              uses: benc-uk/workflow-dispatch@v1
              with:
                  workflow: deploy.yml
                  repo: stuyk/athena-docs-latest
                  token: ${{ secrets.DOCS_PAT }}
                  ref: 'main'
